name: anomaly_detection
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
  - simpleitk
dependencies:
  - python=3.9
  - pip
  - flake8
  - python-wget
  - tqdm
  - cudatoolkit=11.3
  - pytorch>=1.10.1
  - torchvision>=0.11.2
  - matplotlib>=3.3.3
  - pandas>=1.2.0
  - python-wget>=3.2
  - nibabel>=3.2.1
  - dipy>=1.3.0
  - fury>=0.6.1
  - simpleitk>=2.0.2
  - scikit-learn>=0.24.2
  - scikit-image>=0.18.3
  - ipython>=7.18.1
  - tensorboard
  - neovim
  - pip:
    - torchsummary
    - timm
    - wandb
variables:
  DATAROOT: ~/datasets/